### ISSUE TITLE
OFMF mockups all have DMTF copyright.  Need to discuss removing / replacing.

### ISSUE THREAD

**Issue by rahlvers** [OFMFWG/mockups#3]

**Comment by JohnMayfieldHPE** [comment]
JeffH suggest we remove the DMTF copyrights and use OFA Copyrights.  What would the OFA copyrights look like?  
DMTF:      "Copyright 2014-2021 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright."               
OFA:  "Copyright © 2021 OpenFabrics Alliance. All rights reserved. " ?

There are SNIA copyrights in the mockups as well, so we probably need to update all files to a consistent copyright notice.

**Comment by rahlvers** [comment]
That OFA copyright would suffice for now.    The copyright statement here certainly looks like all "All rights reserved" to me: https://downloads.openfabrics.org/WorkGroups/board/bylaws_and_policy/2020_ipr_policy/History/OFA%20Intellectual%20Property%20Rights%20Policy%20v0.91.docx
